# Generated by Django 4.2.2 on 2023-07-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_is_active_useractivatetokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profile',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
