# Generated by Django 4.2.2 on 2023-08-03 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_tweets_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='category',
            field=models.CharField(choices=[('FREE', 'FREE'), ('政治', '政治'), ('IT', 'IT'), ('経済', '経済'), ('哲学', '哲学'), ('人間関係', '人間関係'), ('恋愛', '恋愛')], default='FREE', max_length=50),
        ),
        migrations.AlterField(
            model_name='tweets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 3, 14, 31, 54, 113660, tzinfo=datetime.timezone.utc)),
        ),
    ]
