# Generated by Django 4.2.2 on 2023-08-13 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0006_alter_tweets_created_at_like_tweets_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 12, 5, 16, 527962, tzinfo=datetime.timezone.utc)),
        ),
    ]
