# Generated by Django 4.2.2 on 2023-08-26 04:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0007_alter_tweets_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 4, 38, 17, 826384, tzinfo=datetime.timezone.utc)),
        ),
    ]
